### ISSUE TITLE
Błąd podczas przedtransakcji przy błędnej konfiguracji serwisu

### ISSUE THREAD

**Issue by lstosik** [bluepayment-plugin/bm-sdk#2]
Obecnie leci:
```
PHP Fatal error:  Uncaught TypeError: trim() expects parameter 1 to be string, null given in /vendor/bluepayment-plugin/bm-sdk/src/Transaction/ValueObject/Transaction.php:289
Stack trace:
#0 /vendor/bluepayment-plugin/bm-sdk/src/Transaction/ValueObject/Transaction.php(289): trim()
#1 /vendor/bluepayment-plugin/bm-sdk/src/Hash/HashChecker.php(19): BlueMedia\\Transaction\\ValueObject\\Transaction->getHash()
#2 /vendor/bluepayment-plugin/bm-sdk/src/Transaction/Parser/TransactionResponseParser.php(64): BlueMedia\\Hash\\HashChecker::checkHash()
#3 /vendor/bluepayment-plugin/bm-sdk/src/Transaction/Parser/TransactionResponseParser.php(30): BlueMedia\\Transaction\\Parser\\TransactionResponseParser->parseTransactionInitResponse()
#4 /vendor/bluepayment-plugin/bm-sdk/src/Client.php(117): BlueMedia\\Transaction\\Parser\\TransactionResponseParser->parse()
#5 /SDB-3550.php(7): BlueMedia\\Client->doTransactionInit()
#6 {main}
```
Jeżeli w odpowiedzi na przedtransakcję nie ma Hasha. To oznacza błędną konfigurację serwisu. Szczegóły są w https://jira.blue.pl/projects/SDB/issue/SDB-3550 . 
To jest OK, że SDK się wywala w takiej sytuacji - ale powinno zwrócić jakiś sensowny komunikat błędu - poinformować o błędnej konfiguracji.

**Comment by Karol-BM** [comment]
Fixed in #17
